In [ ]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
df=pd.read_csv("student_performance.csv")
df.head()

Saving student_performance.csv to student_performance (3).csv

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
0,STU0001,Male,15,25,63.8,Bachelor,Yes,Yes,41,67,Yes
1,STU0002,Female,15,2,54.7,Bachelor,Yes,Yes,83,28,No
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No
3,STU0004,Male,16,26,66.8,High School,No,Yes,75,70,Yes
4,STU0005,Female,15,25,73.0,High School,No,Yes,67,77,Yes

In [ ]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
df=pd.read_csv("student_performance.csv")
df = df.fillna(df.mean)
df = df.fillna(df.median)
df = df.fillna(df.mode)

Saving student_performance.csv to student_performance (8).csv

In [ ]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
df=pd.read_csv("student_performance.csv")
df.isnull().sum()

Saving student_performance.csv to student_performance (7).csv

student_id                0
gender                    0
age                       0
study_hours_per_week      0
attendance_rate           0
parent_education        117
internet_access           0
extracurricular           0
previous_score            0
final_score               0
passed                    0
dtype: int64

In [ ]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
df=pd.read_csv("student_performance.csv")
df.tail()

Saving student_performance.csv to student_performance (4).csv

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
495,STU0496,Female,19,6,78.3,Master,No,No,51,27,No
496,STU0497,Female,16,27,61.1,PhD,No,No,47,74,Yes
497,STU0498,Female,18,16,72.3,Master,No,Yes,52,61,Yes
498,STU0499,Male,17,29,91.3,NaN,Yes,No,39,86,Yes
499,STU0500,Male,15,29,75.4,High School,No,Yes,34,74,Yes

In [ ]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
df=pd.read_csv("student_performance.csv")
print('rows: ', df.shape[0])
print('columns: ', df.shape[1])

Saving student_performance.csv to student_performance (6).csv
rows:  500
columns:  11